# Generated by Django 4.0.2 on 2022-07-23 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_emp_delete_emp1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emp',
            new_name='Emp1',
        ),
        migrations.RenameModel(
            old_name='Reg',
            new_name='Reg1',
        ),
    ]
